login:
  path: /login
  controller: App\Controller\SecurityController::loginAction

register:
  path: /register
  controller: App\Controller\RegistrationController::registerAction

home:
  path: /home
  controller: App\Controller\HomeController::homeAction


postPost:
  path: /postPost/{id}
  controller: App\Controller\AddPostController::postAction


deletePost:
    path: /deletePost/{id}
    controller: App\Controller\AddPostController::deletePost

updatePost:
    path: /updatePost/{id}
    controller: App\Controller\AddPostController::updatePost